### PR TITLE
Create 10 Eastern US AVAs, Edit North Fork of Roanoke AVA, Create Eastern Connecticut Highlands AVA (October 2019)

### PR DESCRIPTION
**Pull request by ericallanwest**
Most recent AVA to be established (October 2019). No issue for this AVA exists.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Hi Eric! I'll take a look at these later in the week. If there is no issue for one or more of theses, can you make one so we can track them like the others? Thanks!

**Comment by ericallanwest** [comment]
Also adding the 3 AVAs on Long Island, New York.

**Comment by MicheleTobias** [comment]
Great!  I'm just starting to check the files in this pull request.  Hopefully it won't take too long.

**Comment by MicheleTobias** [comment]
These look pretty good.  There are a couple of things that need another look:

1.  North Fork of Roanoke - are the changes to the polygon because the original data interpreted the instructions differently? Understanding how people are interpreting things differently is helpful in the long term for this project.

1.  3 files have the wrong projection (they have EPSG 4269 but need to have 4326) and have a completely different attribute table:  Long Island, North Fork of Long Island, & The Hamptons Long Island (apparently all "Long Island" files!).

Take a look at these and let me know if you have questions about what I'm seeing.

**Comment by ericallanwest** [comment]
I uploaded the wrong versions of the 3 AVAs for Long Island. The correct versions are commited now.

For the North Fork of Roanoke AVA, I was correcting the problems that I first mentioned in Issue #146.

**Comment by MicheleTobias** [comment]
Getting closer! Long Island & The Hamptons Long Island are throwing an error when I load them in QGIS, but the other file looks good.  Using GeoJSONLint http://geojsonlint.com/ it looks like they have invalid geojson.  I'm not sure what's not right.  I checked the quotes and end of the document, which is a place things tend to go wrong, but they look like the other valid files.

**Comment by kurtishouser** [comment]
For Long Island the issue is with the `approved_maps` and `used_maps` properties. The are several extra double quotes.

**Comment by kurtishouser** [comment]
FYI: The boundary description for the Monticello AVA in this PR is different than the one for issue #135. The CFR was updated Dec 2017.

Issue #152 Outer Coastal Plain also does not match what is currently in the CFR. It was update Dec 2017 as well.

It's something to consider when working on anything in the TBD folder going forward. Update the current issue? Delete it and create a new one with the updated info? Right now these are the only two affected by this.

**Comment by ericallanwest** [comment]
I believe the double quotes issue is fixed with these latest commits.

**Comment by MicheleTobias** [comment]
@kurtishouser , we're trying to finish up the boundaries as they existed when we started the project.  The plan is to eventually have boundaries for every approved version of the AVAs, not just what is the current version.

@ericallanwest in the future, I think it would be helpful for you to use a branch to create your boundaries so you can submit one or two at a time.  It would be easier to keep tabs on what all these files need if they are in separate PRs.

**Comment by MicheleTobias** [comment]
Please stop adding files to this PR.  Submit a separate one with new files so I can finish this one up.

**Comment by MicheleTobias** [comment]
This PR now has a conflict.  I am going to close this PR.  Please resubmit the files as a separate PR or a few at a time.  At this point, there are enough questions about what's going on and conflicts in the data that I think it will be faster to sort this out if we take it one piece at a time.

**Pull request closed without merging**
