### PR TITLE
Added Texoma

### PR DESCRIPTION
**Pull request by ouwxmaniac**
Added the Texoma AVA

This is my first digitize, so I want to ensure I'm doing everything correctly and I've created a geometry of sufficient quality

### CODE REVIEW

**Comment by MicheleTobias** [comment]
The digtizing looks great!  Just a couple of things are missing from the attribute table... Please skim through the original Federal Register document to find the petitioner name (often a person from a winery or association) and the CRF Author (the person who wrote the Federal Register document).  See the avas.geojson file for examples.

**Comment by ouwxmaniac** [comment]
Done!

**Comment by MicheleTobias** [comment]
Great work!

**Comment by MicheleTobias** [comment]
Thank you!

**Pull request merged**
