### PR TITLE
Fix cfr_revision_history for Eola-Amity Hills

### PR DESCRIPTION
**Pull request by kurtishouser**
I removed the two newlines `\n\n` at the end.

Copying directly from the web page and/or PDF (into QGIS?) has introduced a lot of errant `\n` and `\r` characters that should probably be removed. Going forward it might be better to copy from these sources into a text editor like VS Code first so they can be removed.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
It's just a mistake. Thanks for catching it!

**Comment by kurtishouser** [comment]
@MicheleTobias They're copy/paste errors. Multiple property fields are affected.

Two of the Sta. Rita Hills petitioner properties have multiple newline characters. They mirror the line breaks from the PDF.
`"Patrick\nL. Shabram, on behalf of John\nSebastiano Vineyards and Pence Ranch\nVineyards"`
https://www.govinfo.gov/content/pkg/FR-2016-08-22/pdf/2016-19998.pdf
`"A group\nof 11 viticulturists and vintners in the\nestablished Santa Rita Hills viticultural\narea"`
https://www.govinfo.gov/content/pkg/FR-2005-12-07/pdf/05-23682.pdf
There are several other petitioner fields with this issue. approved_maps and boundary_description too. The single newlines mirror the PDF. Double newlines are most likely from the web pages.

It's just something to keep in mind when copying and pasting.

**Comment by MicheleTobias** [comment]
The original attribute were generated with a script that copied information from the eCFR into the files. Yes, this generated some end of line and line breaks that we don't need in the data.  I'm happy to have them fixed when you or someone else finds them if you need it fixed for the way you are using the data. Keep in mind, the purpose of this dataset is for researchers and up to this point, we haven't had a situation that warrants our staff spending time to fix it.

**Comment by kurtishouser** [comment]
Sta. Rita Hills example:
This is what `petitioner` looks like rendered to the screen.

A group
of 11 viticulturists and vintners in the
established Santa Rita Hills viticultural
area

This is what `approved_maps` looks like rendered to the screen.

The appropriate
maps for determining the boundary of
the Sta. Rita Hills viticultural area are
five (5) U.S.G.S. Quadrangle 7.5 Minute
Series maps titled:
(1) "Lompoc, Calif.," edition of 1959
(photorevised in 1982).
(2) "Lompoc Hills, Calif.," edition of
1959 (photoinspected 1971).
(3) "Los Alamos, Calif.," edition of
1959.
(4) "Santa Rosa Hills, Calif.," edition
of 1959 (photoinspected 1978).
(5) "Solvang, Calif.," edition of 1959
(photorevised 1982).

Although it's definitely a problem for me if I choose to display it as part of a web app, I imagine it could have implications for researchers as well.

Again, I'm just bringing it to your attention.

**Comment by MicheleTobias** [comment]
I understand that the end of line characters make new lines. I'm not sure what the discussion continues to be about here.  Yes, ideally the end of line characters aren't there.  I appreciate you fixing problems when you find them.

**Pull request merged**
