### PR TITLE
Southeastern New England

### PR DESCRIPTION
**Pull request by dannyo33**
Moved southeastern_new_england.geojson file from tbd folder to avas folder.
Completed digitization of the AVA in the southeastern_new_england.geojson file.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Great work so far!  Here are some things to update:

The attribute table needs to be filled in as best you can.  At minimum, you need to fill in the following fields;

- created
- petitioner
-cfr_author
- used_maps
- aka is optional, but should be filled in if the AVA has an alternative name

Also, the south and eastern boundary (the square area following the map extent) does not match the description in the text.  Please review and fix this.

**Comment by dannyo33** [comment]
The south and eastern boundary encompasses all of the coastal islands within Massachusetts and Rhode Island. Should I match the outer coastlines of these islands? Clarification for how to fix the south and eastern boundary would be much appreciated. Thank you.

**Comment by MicheleTobias** [comment]
This one is certainly a tricky one!  I believe the intent of the description is to follow the coastline.  That means that each of the islands they talk about needs to be a new polygon with the same attributes.

**Comment by MicheleTobias** [comment]
In the future, let's put questions about a specific AVA in the issue for that AVA so it's all in one place.

**Pull request closed without merging**
