### PR TITLE
Texas Davis Mountains

### PR DESCRIPTION
**Pull request by bsllee**
Digitized boundary for Texas Davis Mountains, TX.

For steps 13 and 14, I followed Cherry Canyon as closely as I could to the point where it meets Grapevine Canyon so that I could proceed in a straight line to the peak of Bear Cave Mountain. I believe that everything else should be correct, thank you so much!

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Hi Brian! This looks like the old version of the data.  The last commit was on June 28th, and I'm pretty sure you've made changes since then.  Make sure you've pushed your new data to your online repository and then submit a new pull request.  I'm happy to help sort this out, so don't hesitate to ask.

**Comment by bsllee** [comment]
Hi Dr. Tobias,

I've definitely made changes to the AVA and thought I committed them before
completing the pull request. Sorry about that! I am trying to commit these
changes before submitting a new pull request, but nothing is showing up in
GitHub for Desktop and I was wondering how to troubleshoot:

[image: image.png]

This is what the AVA should look like from me for future reference:

[image: image.png]

Thank you so much!

Brian

**Comment by bsllee** [comment]
Sorry for another reply, I've also attached a picture of my history on
GitHub Desktop in case that'd be helpful. Thank you so much!

[image: image.png]

**Comment by MicheleTobias** [comment]
Looking at your online repository, your changes haven't been pushed to your repository.  They are on your computer, but your online account doesn't have them yet.  Check your GitHub Desktop to see if the Push button is activated.  If it is, click it to push the changes you've already committed.  The photos in the comments aren't showing up so I hope mine does.

githubpush

**Comment by MicheleTobias** [comment]
I've got the new data after re-opening your pull request.  Looks good so far!  I'll review it and hopefully merge your changes.  You're doing great!  It's very normal for your first AVA to have a couple of revisions.

**Comment by MicheleTobias** [comment]
Ok! Your data contribution is merged with the full dataset.  Congrats on finishing your first boundary!

**Comment by bsllee** [comment]
Thank you so much, I'll pick another one to work on later today!

**Pull request merged**
