### PR TITLE
Create van_duzer_corridor.geojson

### PR DESCRIPTION
**Pull request by sdelong**
I've digitized Van Duzer Corridor even though there isn't a marker file for it.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Thanks!  I'm going to try to get to the remaining pull requests today.  Can you make an issue for this boundary?  That will help me keep track of it like the others.

**Comment by ericallanwest** [comment]
I recently created the issue. It is #472.

**Comment by MicheleTobias** [comment]
Thanks!

**Comment by sdelong** [comment]
Thanks, Eric.  It's not much compared to all the AVAs you're cranking out!

**Comment by ericallanwest** [comment]
This is my last semester of graduate school. It is unlikely I will have time for this project once I complete my degree. So I am doing what I can to get this project across the finish line in the next month or two!

**Comment by MicheleTobias** [comment]
I appreciate both of your contributions!  This dataset would not be even half of what it currently is without contributors from outside of my organization.  The community ownership makes it so much stronger.

**Comment by sdelong** [comment]
Thanks, Michele, this is a wonderful project, as well a huge and difficult one. You must be very happy that Eric got involved. I know I have limited time to contribute.
Eric, you may be named West but you are the Beast of the East!

**Pull request merged**
