### PR TITLE
Upper Mississippi AVA

### PR DESCRIPTION
**Pull request by InnisfreeM**
Created polygon for Upper Missippi AVA from maps and AVA description.

Hopefully everything looks OK.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Hmm... something went awry.  The geojson file is missing all of the features information.  Can you check to make sure you uploaded the file you intended to?

**Comment by MicheleTobias** [comment]
This one looks like it has data in it.  Thanks for sending the updated one.  I'll take a look at it today and hopefully merge it into the rest of the data.

**Comment by MicheleTobias** [comment]
The boundary looks great! There are a couple of things missing from the attribute table I prefer contributors try to find: 

- [ ] Created date

- [ ] Petitioner - who petitioned the ATF to create this AVA?  What is their affiliation?

- [ ] CRF Author - who wrote the final document?  It's always an ATF staff person.

- [ ] Used Maps - which maps did you use to make the boundary?  Sometimes it's the same as the approved maps, but usually there's a substitution of some sort.

The place to look for all of this is here: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c#se27.1.9_1216

**Comment by MicheleTobias** [comment]
Yes, just add that information to the attribute table and then the data should be ready to go.  If you commit the new data, it should show up in the pull request for me to merge.

**Comment by MicheleTobias** [comment]
I finally got some time to look at a couple of pull requests that have been hanging around.  Would you like me to fill in the attribute table?  I realized that some people don't have access to the Hein Online site or other document repositories.

**Comment by InnisfreeM** [comment]
Hi Michele,
Sorry, I just have gotten distracted by other projects. Let me see what I
can do over the weekend. If I don't have access I will let you know.
I.

**Comment by InnisfreeM** [comment]
Also, I could try to train one of my research assistants here to work on
the AVA project if you need help with a particular part of the country.
They are college freshmen and I'm training them in how to use open
streetmap currently. One person has experience with CAD so I think she
could learn QGIS pretty well.
I.

**Comment by InnisfreeM** [comment]
Ok, I finally found the missing info, except who the petitioner was. Where is that supposed to be? https://www.federalregister.gov/documents/2009/06/22/E9-14574/establishment-of-the-upper-mississippi-river-valley-viticultural-area-2007r-055p

**Comment by MicheleTobias** [comment]
This one didn't have a person, but a committee - Upper Mississippi River Valley AVA Committee.  This information typically shows up in the narrative section about how the AVA came to be, usually near the beginning of the document, but they vary a lot.

**Comment by InnisfreeM** [comment]
I have been so slow getting back to this, I'm not sure if the final change, the petitioner, was properly added? Let me know.

**Pull request merged**
