### PR TITLE
Yakima Valley Edit

### PR DESCRIPTION
**Pull request by elistockwell**
10-26-2020 update to Yakima Valley boundary

### CODE REVIEW

**Comment by kurtishouser** [comment]
@elistockwell
You're requesting a merge into the `history-example` branch. I think this needs to be `master` instead.

I also noticed a couple of issues:
`name` needs to be fixed. There's a `2` at the end.
`cfr_revision_history` needs to be changed for the updated boundaries.

@MicheleTobias
Combining current and historical boundaries into a single file is probably not the best option. I think historical boundaries should be maintained in a separate folder with each revision in an individual file. The data set will be more flexible with this approach.

**Comment by MicheleTobias** [comment]
@kurtishouser I asked him to submit this to the history branch to keep things organized for the next stages of this project.

**Comment by kurtishouser** [comment]
@MicheleTobias
Ok, but the new Candy Mountain AVA and the updated Yakima Valley boundaries are part in the same CFR. If Candy Mountain gets merged into master then I would expect the latest Yakima Valley boundaries to be there as well.

**Comment by MicheleTobias** [comment]
@kurtishouser I have a plan to update it all.  Please give me some time to do this.

**Comment by MicheleTobias** [comment]
@elistockwell As we discussed, I'd like you to 

- Review the Petitioner & CFR Author information - check to see if these should be changed.

- Update the Revision History string

- Remove the 2 extra columns added by the merge process you used to combine the two boundaries

**Pull request merged**
