### PR TITLE
Line break fix for #676

### PR DESCRIPTION
**Pull request by labriola**
This is a just a line break fix for walla walla. It seems like an errant line break or two was introduced when fixing #665 

Ideally, I would merge this after #675 to avoid any conflicts or confusion in the commit history with the NA/empty string issues

### CODE REVIEW

**Comment by elistockwell** [comment]
Did you mean to say they were introduced when fixing #675? #665 is Walla Walla History and it looks like that hasn't been addressed yet.

**Comment by labriola** [comment]
Looking at walla wall in master:

https://github.com/UCDavisLibrary/ava/blob/master/avas/walla_walla_valley.geojson

You will see that github can't render it right now. I probably mentioned the wrong issue and can look back through to find the right one, but the JSON invalid. I believe this is due to an extra line break

**Comment by elistockwell** [comment]
Oh I think you meant #664, that makes sense.  Thanks for fixing that!

**Comment by labriola** [comment]
@elistockwell this one has also been rebase and should be merged after #675

**Comment by elistockwell** [comment]
I just noticed the slashes to dashes part of your commit.  I think this is something QGIS does when you input dates sometimes, I remember putting in dates in the correct format and going back to find that it had changed to having slashes.  I will look into it and see how this can be prevented in the future.

**Comment by labriola** [comment]
@elistockwell sounds good. I was going to make a PR later tonight or tomorrow to at least clean up what is there. In my existing PRs I mainly focused on valid_end, but the formatting issues are present in may other date fields. Worse, there is a mix of both styles in each field, so I was attempting to standardize on what (it appears) the project has been doing most recently (dashes).

**Comment by MicheleTobias** [comment]
There's a standard set on the [main readme](https://github.com/UCDavisLibrary/ava/blob/master/README.md) file for formats.  We prescribed dashes, but that's not to say that other programs aren't changing things.

**Comment by MicheleTobias** [comment]
Not file formats... data formats.

**Comment by labriola** [comment]
@MicheleTobias would you mind if I also updated the readme to include the date formats for all date relate fields and indicate those for which null is acceptable? (e.g. valid_start and valid_end)

**Comment by MicheleTobias** [comment]
Good point!  They should all be the same, but I can make that clear for each of them.

**Comment by MicheleTobias** [comment]
I updated the readme, but if you have ideas to make it more clear, feel free to offer suggestions/PRs/etc.

**Pull request merged**
