### PR TITLE
Mississippi Delta AVA #132

### PR DESCRIPTION
**Pull request by amgard**
AVA Mississippi Delta #132

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Hi Anna! Your pull request slipped through the cracks on my to-do list.  I'll start checking it today.  Sorry about the wait!

**Comment by MicheleTobias** [comment]
I think perhaps you sent an older version of the file.  This one has only 3 vertices and the attribute table hasn't been updated.  Can you check and make sure you sent the right data?

**Comment by amgard** [comment]
Yes, I uploaded the incorrect file. Sorry about that

**Comment by amgard** [comment]
I was not sure if I could upload another file in the same pull request so I created a new pull request with the correct polygon and attribute table (I am still learning the ways of GitHub)

**Comment by amgard** [comment]
Fixed in a different branch, made a new pull request. Going to close this one.

**Pull request closed without merging**
