### PR TITLE
Yadkin Valley

### PR DESCRIPTION
**Pull request by ouwxmaniac**
Yadkin valley done. Not sure how you'd like to reconcile differences in county depiction between usgs maps and something like OSM admin boundaries. There's some pretty big differences. Personally, I'd lean on the OSM county boundaries, but used the USGS maps for this If you'd like me to go back and match with OSM, I can.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Let's stick with the USGS maps since that's what the descriptions are based on. Yes, there are sometimes big discrepancies, but that's ok.  We want to follow the legal description as closely as possible.  How that means for reality is another issue.

**Comment by ouwxmaniac** [comment]
The scientist in me twitches every time I see the differences, but I can 100% see your point.

**Comment by MicheleTobias** [comment]
As a scientist too, I completely understand!  The more I work on this project though the more clear it becomes to me that the AVA definitions are mostly not based in science.  And the system of writing physical descriptions based on printed maps has many problems in a digital age.

**Comment by MicheleTobias** [comment]
Thank you for another excellent boundary!

**Pull request merged**
