### PR TITLE
Add Columbia Gorge

### PR DESCRIPTION
**Pull request by KyleWSmith**
I've completed the Columbia Gorge AVA.  Please advise if there are any issues as this is my first AVA and my first time working with Git.  Thanks!
Kyle

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Looks great at first pass!  I'm going to take a closer look tomorrow morning and I'll send you any feedback soon!

**Comment by MicheleTobias** [comment]
I think you're on the right track!  The smoothness of the curves looks good and you're doing well identifying the landmarks from the descriptions.  I'm looking at the section of the boundary in the Parkdale Quad and I can see that the shape is right, but it's not lining up with the 2,000 foot contour line - it's offset.  A couple of things might cause this: 1. you used a map from a different year (that's fine, but it needs to be documented in the attribute table if you do) or 2. there's a projection problem or 3. something else.  
columbiagorge_offset

**Comment by KyleWSmith** [comment]
Thanks for the feedback, Michelle.  I'll verify the map version and projection and get it aligned.

**Comment by KyleWSmith** [comment]
Michele,

I think it fell under #3 - Something else.  I was unable to replicate the problem until I re-downloaded the Parkdale quad and the boundary was then misaligned.  I've corrected it and will submit a new pull request.

**Pull request closed without merging**
