### PR TITLE
Change data type of cfr_index value to a string

### PR DESCRIPTION
**Pull request by kurtishouser**

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Hi Kurtis! Can you explain why this is necessary? Is it different than the other AVA files? Thanks!

**Comment by ericallanwest** [comment]
The quotes around the cfr_index value are getting stripped from some of my files but not others. The [Attribute Data Definitions](https://github.com/UCDavisLibrary/ava/blob/master/README.md#attribute-data-definitions) table doesn't specify what data type cfr_index should be. If it should be a string, then I will double-check my files before submit a pull request.

**Comment by kurtishouser** [comment]
The `cfr_index` is not a floating point number. The value after the period is sequential: `9.159, 9.160, 9.161, ...`. If it's treated as a number any trailing zeros will get dropped so it needs to be a string.

The Node JS CL app I wrote to check for new and updated AVAs caught it. It expects `cfr_index` to be a string and crashed. This is the only one that caused problems so I'm assuming that all the other AVA files are correct (a string).

**Comment by MicheleTobias** [comment]
Thanks for this fix and the explanation!

**Pull request merged**
