### PR TITLE
Use proper Mt Veeder ava_id

### PR DESCRIPTION
**Pull request by rodericj**
There was a missing underscore in the name which did not match with the geojson file in the listing of all avas

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Thanks for your recent pull requests! UC Davis staff are on mandated time off until Jan. 4th. I'll take a look at these sometime that week, work backlog permitting.

**Comment by rodericj** [comment]
Sure. I'm in no rush here. I'm able to reference my branch in my projects.

**Comment by MicheleTobias** [comment]
Is your thinking that it needs 2 underscores because one replaces the . and the other replaces the space in the name?

**Comment by MicheleTobias** [comment]
Oh! I see.  It matches the file name that way.

**Comment by MicheleTobias** [comment]
I'm going to make this change in the mt__veeder.geojson file and regenerate the others.  The states and the avas.geojson files get made with an R script from the individual AVA files.  Thank you for bringing this to my attention!

**Comment by rodericj** [comment]
Got it. I don't care if it's 1 or 2, I just want them the same across the entire data set.

**Comment by MicheleTobias** [comment]
I changed it in the Mt. Veeder ava file.  In the future, these things are better discussed as an issue while you're getting familiar with the structure of a given project.

**Pull request closed without merging**
