### PR TITLE
Niagara escarpment

### PR DESCRIPTION
**Pull request by ekalalip**
resubmitting niagara-escarpement with fixing issue #141. tmp file was removed and used maps were updated.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
I don't see maps on TopoView in the 1:250,000 set that have the names of the maps listed.  They appear to be of the 1:24,000 set.  Are you sure the maps you used were of 1:250,000 scale?

**Comment by ekalalip** [comment]
they are 1:24000. did I mention they are 1:250,000?

**Comment by MicheleTobias** [comment]
It says "(1) Lewiston, New York—Ontario, 1980, 1:25000" for map 1, so that's not correct.  Please fix it and resubmit.

**Comment by MicheleTobias** [comment]
When I downloaded the maps for this AVA, they are actually 1:25,000 scale, which is unusual. You should always check what's printed on the maps.  I will do ahead and fix it in the attribute table.  Please talk to Alex before you do another AVA.

**Pull request merged**
