### PR TITLE
Standardizes valid_end by replacing NA and empty string with null

### PR DESCRIPTION
**Pull request by labriola**
Also addresses an inconsistency in valid_end formatting where slashes were used in place of dashes.  Does not address additional date inconsistencies in valid_start or historic data which will be addressed separately. Relates to #674.

@MicheleTobias so, comparing JSON in a PR is awful. Let me know if you would like me to provide some other form of report or verification to help with this. I verified that all of the geojson parses but happy to do more.

### CODE REVIEW

**Comment by elistockwell** [comment]
So far everything looks good in the PR, the only thing is the edit to avas_by_state/WA_avas.geojson, anything outside the avas folder like the avas_by_state and the avas.geojson file gets generated by code (you can find it in the Rcode folder) so just make those edits to the avas themselves and the changes will be reflected in avas_by_state next time we run the code.

**Comment by labriola** [comment]
Sounds good. Would you like me to fix the PR and pull out that change? I can do so quickly

**Comment by elistockwell** [comment]
That would be great!

**Comment by elistockwell** [comment]
Let me know when you make the edit, I think otherwise we're ready to merge.

**Comment by labriola** [comment]
@elistockwell okay, this one has been rebased on the latest master branch and only has the commits to the avas folder. I am going to go rebase the other PR as well to ensure all of the merges are clean for you

**Comment by elistockwell** [comment]
Perfect, thanks!

**Pull request merged**
