### PR TITLE
AVA Mississippi Delta 

### PR DESCRIPTION
**Pull request by amgard**
This should be the correct polygon with attribute table filled out for Mississippi delta AVA

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Please you review these steps:
(xiii) Then generally northeastward along that contour line to Mississippi Route 3.
(xiv) Then northward along Route 3 to the Tunica County-Tate County line.

With the maps I used, it looks like the line never follows Route 3. It's a small section on the Helena map east of Tunica.

Also, in the AKA column of the attribute table, list the names without quotes with commas in between the names.  The quotes will cause trouble in some queries and are unnecessary.

Let me know if you have questions!

**Comment by amgard** [comment]
I took a look at the polygon and directions again. I follow the Route 3 until the tunica-tate county line as the instructions tell me to do. It appears the county line for tunica-tate is actually the stream, I asked Danny to see what he though and he agrees, maybe I should ask Alex to take a look as well? Perhaps our maps our different? I am using  Helena, scale of 1:250,000, 1955 (revised 1977).

**Comment by MicheleTobias** [comment]
This is what I'm seeing using the same map:  
MississippiDelta_steps13 14
The line should follow the topoline until it hits highway 3, then follow highway 3, but it doesn't seem to.  I think getting another set of eyes on it might help.

**Comment by amgard** [comment]
I was using the wrong edit year for my map, I switched it. Sorry for the confusion on my end. Should be good to go now!

**Pull request merged**
