### PR TITLE
Walla Walla Valley

### PR DESCRIPTION
**Pull request by dannyo33**
Deleted the triangle and updated the petitioner field to the correct format.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Steps 7 & 8 don't seem to be represented well by the boundary in this polygon.  The line doesn't seem to follow any topoline in particular.  Can you clarify either why you digitized it this way, or review and fix it?

**Comment by MicheleTobias** [comment]
I'm also not able to find all of the maps you listed in the Used Maps column.  Are they all 100,000s or are some of them 24000s?

**Comment by dannyo33** [comment]
> 
> 
> Steps 7 & 8 don't seem to be represented well by the boundary in this polygon. The line doesn't seem to follow any topoline in particular. Can you clarify either why you digitized it this way, or review and fix it?

The instructions specify to follow the 2000 ft contour line, however, the 100K maps have contour lines in meters and I would have to trace between to 600 m and 650 m contour lines, therefore, I used the 250K maps to trace the 2000 ft contour line.

**Comment by dannyo33** [comment]
> 
> 
> I'm also not able to find all of the maps you listed in the Used Maps column. Are they all 100,000s or are some of them 24000s?

I am submitting an updated pull request currently that includes the resolution of the maps used. The second two maps are 250K resolution. No 24K maps were used.

**Comment by MicheleTobias** [comment]
When there is a question or problem with any of the steps for creating a boundary, please make a note of the problem and your proposed solution in the issue for that AVA so we have a record of them.

**Comment by MicheleTobias** [comment]
I need you to write the map scale in standard format - for example: 1:100,000.  Also, you need to review this pull request with Alex before you submit it.  Your geojson file has become non-standard because of github version issues that have been introduced.

**Pull request closed without merging**
