### PR TITLE
Completed Mimbres Valley AVA.

### PR DESCRIPTION
**Pull request by APRios**
Completed Mimbres Valley AVA. Found error in Item #37. Final not as described in original petition. Item #41 does not line up as described. Maintained boundary for #37 and #41 as described.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Thanks for the boundary and the heads-up about the description!

**Comment by MicheleTobias** [comment]
Do you have a list of the maps you used to make the boundary?  The "used maps" list looks like it's pretty much the same as the "approved maps" but I don't think all of those are available.

**Comment by APRios** [comment]
All of the maps listed in "Approved maps" are the series and edition I used except for two.  Map 5 "Capital Dome," is misspelled in the description and should read "Capitol Dome" with an "o." Map 11 "Deming West" is not identified as "photoinspected 1972" but is stamped with APR 17 1967. All other maps are as listed. I hope this helps.

**Comment by MicheleTobias** [comment]
Yes, thanks!

**Pull request merged**
