### PR TITLE
Western conn. highlands

### PR DESCRIPTION
**Pull request by Alexenia**
request to merge with master for Western Connecticut Highlands.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
This looks great!

**Comment by kurtishouser** [comment]
I just pulled down the latest master and imported the data into my database. It appears that this AVA file has two elements in the `features` array instead of just one. The first element has the placeholder triangle polygon, the second has the new boundaries.

**Comment by MicheleTobias** [comment]
Thanks.  I'll look into it.

**Comment by MicheleTobias** [comment]
I fixed it.  The extra polygon slipped in in my excitement that we were finally done with this one (it's been a challenging boundary).  It's fixed now and the avas.geojson file is updated.

**Pull request merged**
