### PR TITLE
Adding Eastern Connecticut Highlands AVA and Martha's Vineyard AVA

### PR DESCRIPTION
**Pull request by ericallanwest**
The linked issues are #468 and #122. The Eastern Connecticut Highlands AVA is adjacent to the already-submitted Southeastern New England AVA. The Martha's Vineyard AVA is within the Southeastern New England AVA but does not share any borders with it.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Quick observation about Martha's Vineyard that you can probably explain... it looks like the border doesn't match with the shoreline in the areas where the map is labeled "Vineyard Haven Harbor" and "Edgartown".  It cuts across the water.  Any thoughts?

And int he "used maps", the text is copied from the "approved maps" section, which usually works, but here it has some extra text that's not needed.

**Comment by ericallanwest** [comment]
I was unsure how to handle the many inland bays and ponds and harbors, so I looked to the [TIGER Coastline Shapefile](https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2019&layergroup=Coastline) for guidance. I can edit the boundary to exclude those inland features if desired.

As far as the extra text, the wording for this AVA is unusual because it does not use bullet points to refer to individual maps or boundary instructions. It is very similar to the Isle St. George AVA, which also uses a single map and refers to the shoreline of an island.

**Comment by MicheleTobias** [comment]
I'd prefer to only use the information on the approved maps if we can.  Because the description says to follow the shoreline of the two specific islands, I'm thinking the end result should look more like the boundary of Southeastern New England in that area.  Most of the boundary is petty similar to that one.  

For the used maps, I would probably put something like " U.S.G.S. map, “Providence, R.I.; Mass.; Conn.; N.Y.;” scaled 1:250,000, edition of 1947 revised 1969".  The approved maps attribute could even be shortened to that.

**Comment by sdelong** [comment]
Hi Michele, given your background in coastal biogeomorphology, you know that the shorelines of 1969 no longer exist.  Using the approved maps make it a proper historic document, but in practical terms, anyone making a map of Martha's Vineyard AVA would use a contemporary shoreline, probably the same one used for a base map.

**Comment by MicheleTobias** [comment]
I completely agree that the coastlines are constantly changing, but the definition of the AVA boundary is so many miles from the line marked on the map, if I'm understanding what they meant correctly.

**Comment by ericallanwest** [comment]
The boundary I submitted is admittedly a bit clunky. I will add more detail so it passes the eye test.

**Comment by ericallanwest** [comment]
The detail of the Martha's Vineyard boundary is enhanced and the "approved maps" and "used maps" attributes are updated.

**Pull request merged**
