### PR TITLE
Tip of the Mitt

### PR DESCRIPTION
**Pull request by sierramabanta**
Tip of the Mitt #227 is complete.

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Hi Sierra!  Are you ready for me to review this one again?

**Comment by sierramabanta** [comment]
Hi Michele,

It would be appreciated! I’ve had a couple people look at it so it should
be good to go. Please let me know what you think!

Sierra

**Comment by MicheleTobias** [comment]
Much improved!  Thanks for taking the time to fix the issues!

**Comment by sierramabanta** [comment]
Yahooo! Thank you for checking :-)

**Pull request closed without merging**
