### PR TITLE
Aesthetical fixed to ava webmap and removed unnecessary Jekyll files. 

### PR DESCRIPTION
**Pull request by erklopez**
- Changed the color of the map data to be more cohesive with the theme
- Removed scroller from iframe on the map in Explore the Data issue #779 
- Removed unnecessary Jekyll files issue #809

### CODE REVIEW

**Comment by kurtishouser** [comment]
It appears that `docs/.jekyll-cache/` & `docs/_site` are still present. I guess they will have to be removed manually instead of relying on `.gitignore`.

This command should remove them and prevent git from tracking them in the future:
`git rm -r docs/.jekyll-cache/ docs/_site`

**Comment by MicheleTobias** [comment]
@erika try using the commandline to remove the files. 
`cd path/to/your/repo
git rm file.extension
`
Then do you your commit and push

**Comment by erklopez** [comment]
Is it possible that I need to remove them from the .gitignore before trying to use git rm? I am getting that the pathspec did not match any files

**Comment by kurtishouser** [comment]
Try using the command I provided. Both folders need to be completely removed. Make sure the Jekyll dev server is stopped first.

`git rm -r foldername/` removes the folder and all contents. The `-r` is for recursive delete.

**Pull request merged**
