### PR TITLE
Sonoma Coast

### PR DESCRIPTION
**Pull request by amberreyes**
Here's the Sonoma Coast AVA boundary!

### CODE REVIEW

**Comment by MicheleTobias** [comment]
The new boundary looks great! Github is giving me trouble about the avas.geojson file because it's older than what's in the current UCD repo.  Can you delete it and resubmit?

**Comment by amberreyes** [comment]
That's strange, I didn't include the avas.geojson file when I submitted it. So, I can't see anything to delete on my end.

**Comment by MicheleTobias** [comment]
I met with Alex Mandel to figure out what is causing the problem.  It looks like your fork needs to be updated so that it matches the UCD AVA repo before you do your pull request.  Here are some instructions for how to update your fork: https://help.github.com/articles/syncing-a-fork/  I'm going to close this pull request and when you're ready submit the Sonoma Coast AVA again.

**Comment by MicheleTobias** [comment]
Whoops! The link is for instructions on how to do it with the command line tools.  It looks like there isn't an easy way to do it with the desktop tool.  You might need to make a new fork.

**Comment by MicheleTobias** [comment]
I wonder if you can make a branch of the  UCD AVA repo.  Open the UCD repo in GitHub Desktop (there's a green button on the home page of the repo that will do it automatically for you) and see if you can make a branch (it's in the tools... I have an updated version of the desktop tool so I can't tell you what the process is in a helpful way right now, but I remember it being pretty findable in your version).  If you can do that, keeping your branch up to date will be easier than a fork.  Let me know if that works.

**Comment by amberreyes** [comment]
Is it the clone/download button that's supposed to open it in the GitHub Desktop? Because that's the one I clicked but it doesn't look like it changed anything.

**Comment by MicheleTobias** [comment]
Hmm... well we'll figure it out on Tuesday.  I the mean time you can keep digitizing and we'll figure out how to make the pull request thing work when we're all back in the office.

**Comment by amberreyes** [comment]
Sounds good!

**Comment by MicheleTobias** [comment]
I found it!  Here's how to update your fork: https://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381  I just tried it with my old fork and it looks like it works.

Replace "me" with "amberreyes" (your account), "someone" with "UCDavisLibrary" (the UCD account), and "foobar" with "AVA" (the name of the project/repository).

**Pull request closed without merging**
