### PR TITLE
Shawnee_hills#197

### PR DESCRIPTION
**Pull request by Alexenia**

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Hi Alex! I just checked the attribute table and you're missing the CRF author.  This is typically mentioned towards the end of the document, often just before the boundary description.  Take another look and see if you can find it.

**Comment by MicheleTobias** [comment]
Ok, the digitizing looks great!  Alex wrote out the instructions for the saving geojson work-around in issue #415 so once you save the attribute table with the CRF Author, I will be able to merge your pull request.

**Comment by Alexenia** [comment]
Hi Michele,

I just send a pull request and hopefully the attribute table will be updated. Please let me know how it goes, thank you.

**Comment by MicheleTobias** [comment]
Success!  It's there!  Congrats on your first submission!  And thank you for your patience in figuring out what was going wrong with saving the geojson files.  It will eventually make QGIS better since what we found will get reported to the developers who will hopefully find a fix.

**Pull request merged**
